### ISSUE TITLE
Something wrong in train_Semi_Mamba_UNet.py

### ISSUE THREAD

**Issue by onion-LHJ** [ziyangwang007/Mamba-UNet#25]
When I ran train_Semi_Mamba_UNet.py, there is a bug:
Traceback (most recent call last):
  File "train_Semi_Mamba_UNet.py", line 396, in <module>
    train(args, snapshot_path)
  File "train_Semi_Mamba_UNet.py", line 183, in train
    model1.train()
NameError: name 'model1' is not defined

And then I check the code ,notice that :
![微信截图_20240625152742](https://github.com/ziyangwang007/Mamba-UNet/assets/59589865/6faedec1-8fa8-4758-9c02-688f5009b6e4)

I would  be most grateful.if u could tell me what model1 should be .Thanks again for ur great work.

**Comment by xskdjs444** [comment]
Hi, are you sloved this problem? this problem is caused by two model2 are definitioned. So you can ues function of create_model to definition model1 such as UNet . Hope this will help you!

**Comment by Lxycherryup** [comment]
(vmunet) liu@liu-ubuntu:~/lxy/Mamba-UNet-main/Mamba-UNet-main/code$ python test_2D_fully.py --root_path ../data/ACDC --exp ACDC/Semi_Mamba_UNet --model mambaunet
test_2D_fully.py:12: DeprecationWarning: Please use `zoom` from the `scipy.ndimage` namespace, the `scipy.ndimage.interpolation` namespace is deprecated.
  from scipy.ndimage.interpolation import zoom
=> merge config from ../code/configs/swin_tiny_patch4_window7_224_lite.yaml
../model/ACDC/Semi_Mamba_UNet_3/mambaunet/mambaunet_best_model.pth
Traceback (most recent call last):
  File "test_2D_fully.py", line 124, in <module>
    metric = Inference(FLAGS)
  File "test_2D_fully.py", line 104, in Inference
    net.load_state_dict(torch.load(save_mode_path))
AttributeError: 'NoneType' object has no attribute 'load_state_dict'
Hello there! I’m reaching out for some guidance on how to test the Semi_Mamba_UNet model effectively. I’d appreciate any step-by-step advice or recommendations on best practices for running and evaluating it. Thanks so much for your help!
